name: Light for photo
favicon: null
layout_spectrum: 0.24462
typography_spectrum: 0.38293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f3f4'
    - '#b4c5d5'
    - '#151d19'
    - '#646e74'
    - '#364754'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
